version: '3.4'

volumes:
  server-db-OasisData:
  celery-db-OasisData:
  filestore-OasisData:

x-oasis-env: &oasis-env
  OASIS_ADMIN_USER: admin
  OASIS_ADMIN_PASS: password
  OASIS_DEBUG: ${DEBUG:-0}
  OASIS_RABBIT_HOST: rabbit
  OASIS_RABBIT_PORT: 5672
  OASIS_RABBIT_USER: rabbit
  OASIS_RABBIT_PASS: rabbit
  OASIS_SERVER_DB_HOST: server-db
  OASIS_SERVER_DB_PASS: oasis
  OASIS_SERVER_DB_USER: oasis
  OASIS_SERVER_DB_NAME: oasis
  OASIS_SERVER_DB_PORT: 5432
  OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
  OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
  OASIS_CELERY_DB_HOST: celery-db
  OASIS_CELERY_DB_PASS: password
  OASIS_CELERY_DB_USER: celery
  OASIS_CELERY_DB_NAME: celery
  OASIS_CELERY_DB_PORT: 5432
  STARTUP_RUN_MIGRATIONS: 'true'

services:
  server:
   restart: always
   image: coreoasis/api_server:1.28.5
   ports:
     - 8000:8000
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     <<: *oasis-env
   volumes:
     - filestore-OasisData:/shared-fs:rw

  worker-monitor:
   restart: always
   image: coreoasis/api_server:1.28.5
   command: [wait-for-server, 'server:8000', celery, -A, src.server.oasisapi, worker, --loglevel=INFO]
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     <<: *oasis-env
   volumes:
     - filestore-OasisData:/shared-fs:rw
  worker:
    restart: always
    image: coreoasis/oasis_deterministic_worker:1.28.5
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     <<: *oasis-env
     OASIS_MODEL_SUPPLIER_ID: OasisLMD
     OASIS_MODEL_ID: DeterministicModel
     OASIS_MODEL_VERSION_ID: 1
     OASIS_MODEL_DATA_DIRECTORY: /home/worker/model
    volumes:
     - filestore-OasisData:/shared-fs:rw
     - ../keys_data:/var/oasis/keys_data:rw
     - ../model_data:/var/oasis/model_data:rw

  server-db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: oasis
      POSTGRES_USER: oasis
      POSTGRES_PASSWORD: oasis
    volumes:
      - server-db-OasisData:/var/lib/postgresql/data:rw

  celery-db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: celery
      POSTGRES_USER: celery
      POSTGRES_PASSWORD: password
    volumes:
      - celery-db-OasisData:/var/lib/postgresql/data:rw

  rabbit:
    restart: always
    image: rabbitmq:3.8.14-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - 5672:5672
      - 15672:15672

  shiny_proxy:
    restart: always
    container_name: oasisui_proxy
    image: coreoasis/oasisui_proxy:1.11.7
    ports:
     - 8080:8080
    environment:
     #- API_IP=<FOR_REMOTE_IPs>
     - UI_DOCKER_IMAGE=coreoasis/oasisui_app:1.11.7
     - API_PORT=8000
     - API_VERSION=v1
     - API_SHARE_FILEPATH=./downloads
     - OASIS_ENVIRONMENT=oasis_localhost
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - shiny-net

networks:
  shiny-net:
    external: true

